### ISSUE TITLE
Plugin "config-registry" does not offer installation for this platform

### ISSUE THREAD

**Issue by sharjilk** [mumoshu/kubeconf#1]
When I run `kubectl krew install config-registry`, it gives below error.

```
Installing plugin: config-registry
W0107 11:02:21.832092   11509 install.go:164] failed to install plugin "config-registry": plugin "config-registry" does not offer installation for this platform
F0107 11:02:21.832136   11509 root.go:79] failed to install some plugins: [config-registry]: plugin "config-registry" does not offer installation for this platform
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x14000134001, 0x14000175700, 0xa4, 0xf2)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xac
k8s.io/klog/v2.(*loggingT).output(0x102bba900, 0x14000000003, 0x0, 0x0, 0x140000f61c0, 0x10292d2e5, 0x7, 0x4f, 0x1400017de00)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x164
k8s.io/klog/v2.(*loggingT).printDepth(0x102bba900, 0x14000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0x1400009b4d0, 0x1, 0x1)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x120
k8s.io/klog/v2.(*loggingT).print(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
	/home/runner/work/krew/krew/cmd/krew/cmd/root.go:79 +0x224
main.main()
	/home/runner/work/krew/krew/cmd/krew/main.go:25 +0x3c

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x102bba900)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0x128
```

On checking `kubectl krew search config-registry`, it says unavailable for darwin/arm64

```
NAME             DESCRIPTION                            INSTALLED
config-registry  Switch between registered kubeconfigs  unavailable on darwin/arm64
```

How to install config-registry on mac m1 chip?

**Comment by mumoshu** [comment]
@sharjilk Thanks for reporting! I don't have a M1 mac but probably it works after you've added darwin/arm64 to https://github.com/mumoshu/config-registry/blob/6305acab533cd57b967b7504b33c09a5a551b9e3/.krew-release-bot.yaml#L26. Would you mind contributing changes to that file?

**Comment by sharjilk** [comment]
Thanks @mumoshu, please check the pull request.

**Comment by mumoshu** [comment]
@sharjilk https://github.com/mumoshu/config-registry/releases/tag/v0.2.2 has been released with your contribution! I've verified that a darwin/arm64 archive is available in the release assets. That, in combination with your contribution to krew-bot-config yaml, you should be able to install this plugin on M1 mac now. Would you mind confirming?

**Comment by sharjilk** [comment]
@mumoshu Issue has been fixed. Now I am able to install it on M1 chip mac.

**Comment by mumoshu** [comment]
@sharjilk Great! Thanks again for your contribution. Closing as resolved 🎉
